import { ModeConfig } from './types';

export const APP_MODES: Record<string, ModeConfig> = {
  interview: {
    id: 'interview',
    name: 'Entrevistas & Podcasts',
    icon: '🎙️',
    description: 'Para jornalistas e criadores de conteúdo.',
    defaultButtons: [
      { id: 'int-1', icon: '🔥', label: 'Citação', type: 'quote', tooltip: 'Marca uma fala de destaque para usar como citação.' },
      { id: 'int-2', icon: '😢', label: 'Emoção', type: 'emotion', tooltip: 'Registra um momento de forte emoção na entrevista.' },
      { id: 'int-3', icon: '⚠️', label: 'Off-the-Record', type: 'action', tooltip: 'Marca um trecho que não deve ser publicado.' },
      { id: 'int-4', icon: '🤥', label: 'Fact-Check', type: 'action', tooltip: 'Sinaliza uma informação que precisa ser checada.' },
      { id: 'int-5', icon: '✂️', label: 'Cortar', type: 'cut', tooltip: 'Indica um trecho que deve ser cortado na edição.' },
      { id: 'int-6', icon: '🤫', label: 'Silêncio', type: 'action', tooltip: 'Marca um momento de pausa ou silêncio longo.' },
      { id: 'int-7', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Adiciona uma nota ou comentário livre.' },
      { id: 'int-8', icon: '💡', label: 'Pergunta Boa', type: 'action', tooltip: 'Destaca uma pergunta que gerou uma ótima resposta.' },
      { id: 'int-9', icon: '😂', label: 'Riso', type: 'action', tooltip: 'Marca um momento de descontração ou risada.' },
      { id: 'int-10', icon: '🛑', label: 'Interrupção', type: 'action', tooltip: 'Sinaliza uma interrupção na fala.' },
    ],
  },
  lecture: {
    id: 'lecture',
    name: 'Palestras & Aulas',
    icon: '👨‍🏫',
    description: 'Foco em retenção de conhecimento acadêmico.',
    defaultButtons: [
      { id: 'lec-1', icon: '🚨', label: 'Cai na Prova', type: 'action', tooltip: 'Marca um assunto importante para avaliações.' },
      { id: 'lec-2', icon: '❓', label: 'Não Entendi', type: 'action', tooltip: 'Sinaliza um trecho confuso para revisar depois.' },
      { id: 'lec-3', icon: '📚', label: 'Referência', type: 'action', tooltip: 'Marca a indicação de um livro, artigo ou autor.' },
      { id: 'lec-4', icon: '📅', label: 'Data da Prova', type: 'action', tooltip: 'Registra o anúncio de uma data importante.' },
      { id: 'lec-5', icon: '🖼️', label: 'Novo Slide', type: 'action', tooltip: 'Indica a mudança para um novo slide ou tópico.' },
      { id: 'lec-6', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Adiciona uma anotação pessoal.' },
      { id: 'lec-7', icon: '🤔', label: 'Dúvida', type: 'action', tooltip: 'Marca uma dúvida feita por um aluno.' },
      { id: 'lec-8', icon: '💡', label: 'Exemplo', type: 'action', tooltip: 'Destaca um exemplo prático dado pelo professor.' },
      { id: 'lec-9', icon: '📝', label: 'Tarefa', type: 'action', tooltip: 'Registra um trabalho ou exercício passado.' },
      { id: 'lec-10', icon: '⏸️', label: 'Pausa', type: 'action', tooltip: 'Marca o início de um intervalo.' },
    ],
  },
  meeting: {
    id: 'meeting',
    name: 'Reuniões Corporativas',
    icon: '💼',
    description: 'Gera atas automáticas e delega tarefas.',
    defaultButtons: [
      { id: 'mtg-1', icon: '✅', label: 'Decisão', type: 'decision', tooltip: 'Registra uma decisão tomada pelo grupo.' },
      { id: 'mtg-2', icon: '📌', label: 'Action Item', type: 'action', tooltip: 'Marca uma tarefa que precisa ser executada.' },
      { id: 'mtg-3', icon: '👤', label: 'Delegação', type: 'person', tooltip: 'Atribui uma responsabilidade a alguém.' },
      { id: 'mtg-4', icon: '💰', label: 'Orçamento', type: 'action', tooltip: 'Sinaliza uma discussão sobre custos ou verba.' },
      { id: 'mtg-5', icon: '🧱', label: 'Blocker', type: 'action', tooltip: 'Marca um impedimento ou problema no projeto.' },
      { id: 'mtg-6', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Adiciona uma nota livre à ata.' },
      { id: 'mtg-7', icon: '💡', label: 'Ideia', type: 'action', tooltip: 'Destaca uma sugestão ou ideia nova.' },
      { id: 'mtg-8', icon: '🔄', label: 'Follow-up', type: 'action', tooltip: 'Marca um assunto que precisa de acompanhamento.' },
      { id: 'mtg-9', icon: '👍', label: 'Aprovação', type: 'action', tooltip: 'Registra a aprovação de uma etapa ou projeto.' },
      { id: 'mtg-10', icon: '⏳', label: 'Prazo', type: 'action', tooltip: 'Sinaliza a definição de uma data de entrega.' },
    ],
  },
  medical_doctor: {
    id: 'medical_doctor',
    name: 'Consulta Médica (Médico)',
    icon: '🩺',
    description: 'Transforma a conversa em prontuário clínico.',
    defaultButtons: [
      { id: 'med-doc-1', icon: '💊', label: 'Prescrição', type: 'action', tooltip: 'Marca a indicação de um medicamento.' },
      { id: 'med-doc-2', icon: '🤧', label: 'Sintoma', type: 'action', tooltip: 'Registra um sintoma relatado pelo paciente.' },
      { id: 'med-doc-3', icon: '🩺', label: 'Diagnóstico', type: 'decision', tooltip: 'Marca a definição de uma hipótese diagnóstica.' },
      { id: 'med-doc-4', icon: '📅', label: 'Retorno', type: 'action', tooltip: 'Sinaliza o agendamento de uma nova consulta.' },
      { id: 'med-doc-5', icon: '📋', label: 'Pedir Exame', type: 'action', tooltip: 'Registra a solicitação de exames.' },
      { id: 'med-doc-6', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Adiciona uma observação clínica.' },
      { id: 'med-doc-7', icon: '⚠️', label: 'Alergia', type: 'action', tooltip: 'Destaca uma alergia informada pelo paciente.' },
      { id: 'med-doc-8', icon: '📖', label: 'Histórico', type: 'action', tooltip: 'Marca uma informação do histórico médico.' },
      { id: 'med-doc-9', icon: '➡️', label: 'Encaminhamento', type: 'action', tooltip: 'Registra o encaminhamento para outro especialista.' },
      { id: 'med-doc-10', icon: '🚨', label: 'Alerta', type: 'action', tooltip: 'Sinaliza um sinal de alerta (red flag).' },
    ],
  },
  medical_patient: {
    id: 'medical_patient',
    name: 'Consulta Médica (Paciente)',
    icon: '🧑‍⚕️',
    description: 'Gera um resumo claro e orientações da consulta.',
    defaultButtons: [
      { id: 'med-pat-1', icon: '❓', label: 'Dúvida', type: 'comment', tooltip: 'Marca uma pergunta feita ao médico.' },
      { id: 'med-pat-2', icon: '💊', label: 'Remédio', type: 'action', tooltip: 'Registra a explicação sobre como tomar um remédio.' },
      { id: 'med-pat-3', icon: '🤧', label: 'Sintoma', type: 'action', tooltip: 'Marca o momento em que você explica o que está sentindo.' },
      { id: 'med-pat-4', icon: '📅', label: 'Retorno', type: 'action', tooltip: 'Sinaliza quando você deve voltar.' },
      { id: 'med-pat-5', icon: '📋', label: 'Exame', type: 'action', tooltip: 'Registra as instruções para fazer um exame.' },
      { id: 'med-pat-6', icon: '💡', label: 'Dica', type: 'decision', tooltip: 'Destaca um conselho ou orientação do médico.' },
      { id: 'med-pat-7', icon: '🤕', label: 'Dor', type: 'action', tooltip: 'Marca a descrição de uma dor específica.' },
      { id: 'med-pat-8', icon: '🥗', label: 'Dieta', type: 'action', tooltip: 'Registra orientações sobre alimentação.' },
      { id: 'med-pat-9', icon: '🏃', label: 'Exercício', type: 'action', tooltip: 'Marca recomendações de atividades físicas.' },
      { id: 'med-pat-10', icon: '🚨', label: 'Alerta', type: 'action', tooltip: 'Sinaliza algo que você deve prestar muita atenção.' },
    ],
  },
  writing: {
    id: 'writing',
    name: 'Criação Literária',
    icon: '✍️',
    description: 'Para roteiristas e autores construírem a história.',
    defaultButtons: [
      { id: 'wrt-1', icon: '👤', label: 'Personagem', type: 'person', tooltip: 'Marca o desenvolvimento de um personagem.' },
      { id: 'wrt-2', icon: '🗺️', label: 'Worldbuilding', type: 'location', tooltip: 'Registra detalhes sobre o universo da história.' },
      { id: 'wrt-3', icon: '🤯', label: 'Plot Twist', type: 'action', tooltip: 'Sinaliza uma reviravolta na trama.' },
      { id: 'wrt-4', icon: '🕳️', label: 'Furo de Roteiro', type: 'action', tooltip: 'Marca um possível erro de continuidade ou lógica.' },
      { id: 'wrt-5', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Adiciona uma nota criativa.' },
      { id: 'wrt-6', icon: '🗣️', label: 'Diálogo', type: 'action', tooltip: 'Destaca uma ideia para um diálogo marcante.' },
      { id: 'wrt-7', icon: '⚔️', label: 'Conflito', type: 'action', tooltip: 'Registra a tensão ou conflito principal da cena.' },
      { id: 'wrt-8', icon: '🤝', label: 'Resolução', type: 'action', tooltip: 'Marca como um problema será resolvido.' },
      { id: 'wrt-9', icon: '💥', label: 'Cena de Ação', type: 'action', tooltip: 'Sinaliza o planejamento de uma cena de ação.' },
      { id: 'wrt-10', icon: '💡', label: 'Ideia', type: 'action', tooltip: 'Destaca uma inspiração repentina.' },
    ],
  },
  journalism: {
    id: 'journalism',
    name: 'Jornalismo de Campo',
    icon: '🎤',
    description: 'Acelera a ilha de edição na TV.',
    defaultButtons: [
      { id: 'jor-1', icon: '🎥', label: 'B-Roll', type: 'action', tooltip: 'Marca imagens de cobertura (B-Roll).' },
      { id: 'jor-2', icon: '🌟', label: 'VIP', type: 'person', tooltip: 'Sinaliza a aparição de uma pessoa importante.' },
      { id: 'jor-3', icon: '🎙️', label: 'Polêmica', type: 'action', tooltip: 'Destaca uma declaração controversa.' },
      { id: 'jor-4', icon: '💥', label: 'Tumulto', type: 'action', tooltip: 'Marca um momento de confusão ou ação intensa.' },
      { id: 'jor-5', icon: '📝', label: 'Stand-up', type: 'action', tooltip: 'Registra a passagem do repórter (Stand-up).' },
      { id: 'jor-6', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Adiciona uma nota para o editor.' },
      { id: 'jor-7', icon: '🗣️', label: 'Entrevista', type: 'action', tooltip: 'Marca o início de uma sonora/entrevista.' },
      { id: 'jor-8', icon: '✅', label: 'Fato', type: 'action', tooltip: 'Sinaliza um dado ou fato importante.' },
      { id: 'jor-9', icon: '📍', label: 'Local', type: 'location', tooltip: 'Registra a mudança de locação.' },
      { id: 'jor-10', icon: '🚨', label: 'Urgente', type: 'action', tooltip: 'Destaca uma informação de última hora (Breaking News).' },
    ],
  },
  cinema: {
    id: 'cinema',
    name: 'Set de Filmagem',
    icon: '🎬',
    description: 'Claquete digital e assistente de continuidade.',
    defaultButtons: [
      { id: 'cin-1', icon: '🟢', label: 'Ação / Corta', type: 'cinema_action', color: 'Red', tooltip: 'Marca o início e o fim de um take útil.' },
      { id: 'cin-2', icon: '⭐', label: 'Circle Take', type: 'cinema_good', color: 'Green', tooltip: 'Sinaliza que este foi um take bom (aprovado).' },
      { id: 'cin-3', icon: '🔴', label: 'Erro/Problema', type: 'cinema_error', color: 'Orange', tooltip: 'Registra um erro durante a gravação.' },
      { id: 'cin-4', icon: '📝', label: 'Nota de Cont.', type: 'cinema_note', color: 'Cyan', tooltip: 'Adiciona uma observação de continuidade.' },
      { id: 'cin-5', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Nota geral para a pós-produção.' },
      { id: 'cin-6', icon: '❌', label: 'Falso', type: 'cinema_error', color: 'Orange', tooltip: 'Marca um take falso ou interrompido.' },
      { id: 'cin-7', icon: '🔇', label: 'Áudio Ruim', type: 'cinema_error', color: 'Orange', tooltip: 'Sinaliza um problema na captação de som.' },
      { id: 'cin-8', icon: '🔍', label: 'Foco', type: 'cinema_error', color: 'Orange', tooltip: 'Registra um erro de foco na câmera.' },
      { id: 'cin-9', icon: '💡', label: 'Luz', type: 'cinema_error', color: 'Orange', tooltip: 'Sinaliza uma falha ou mudança na iluminação.' },
      { id: 'cin-10', icon: '🎬', label: 'Direção', type: 'cinema_note', color: 'Cyan', tooltip: 'Nota específica do diretor para a montagem.' },
    ],
  },
};
