import { ModeConfig } from './types';

export const APP_MODES: Record<string, ModeConfig> = {
  // --- Category: Produção de Cinema
  cinema: {
    id: 'cinema',
    name: 'Set de Filmagem',
    icon: '🎬',
    category: '🎬 Produção de Cinema',
    description: 'Claquete digital e assistente de continuidade de set.',
    defaultButtons: [
      { id: 'cin-1', icon: '🟢', label: 'Ação / Corta', type: 'cinema_action', color: 'Red', tooltip: 'Marca o início e o fim de um take útil.' },
      { id: 'cin-2', icon: '⭐', label: 'Circle Take', type: 'cinema_good', color: 'Green', tooltip: 'Sinaliza que este foi um take bom (aprovado).' },
      { id: 'cin-3', icon: '🔴', label: 'Erro/Problema', type: 'cinema_error', color: 'Orange', tooltip: 'Registra um erro durante a gravação.' },
      { id: 'cin-4', icon: '📝', label: 'Nota de Cont.', type: 'cinema_note', color: 'Cyan', tooltip: 'Adiciona uma observação de continuidade.' },
      { id: 'cin-5', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Nota geral para a pós-produção.' },
      { id: 'cin-6', icon: '❌', label: 'Falso', type: 'cinema_error', color: 'Orange', tooltip: 'Marca um take falso ou interrompido.' },
      { id: 'cin-7', icon: '🔇', label: 'Áudio Ruim', type: 'cinema_error', color: 'Orange', tooltip: 'Sinaliza um problema na captação de som.' },
      { id: 'cin-8', icon: '🔍', label: 'Foco', type: 'cinema_error', color: 'Orange', tooltip: 'Registra um erro de foco na câmera.' },
      { id: 'cin-9', icon: '💡', label: 'Luz', type: 'cinema_error', color: 'Orange', tooltip: 'Sinaliza uma falha ou mudança na iluminação.' },
      { id: 'cin-10', icon: '🎬', label: 'Direção', type: 'cinema_note', color: 'Cyan', tooltip: 'Nota específica do diretor para a montagem.' },
    ],
  },
  table_read: {
    id: 'table_read',
    name: 'Leitura de Roteiro (Table Read)',
    icon: '📖',
    category: '🎬 Produção de Cinema',
    description: 'Anote feedbacks de ritmo, mudanças em falas e atuações.',
    defaultButtons: [
      { id: 'tr-1', icon: '🎭', label: 'Interp. Incrível', type: 'action', tooltip: 'Destaque de voz ou emoção do ator excelente.' },
      { id: 'tr-2', icon: '💡', label: 'Ajuste Fala', type: 'action', color: 'Green', tooltip: 'Ideia para mutar, simplificar ou aprimorar piadas/falas.' },
      { id: 'tr-3', icon: '⏱️', label: 'Ajuste Tempo', type: 'action', tooltip: 'Ritmo ou pausa que se estendeu além do esperado.' },
      { id: 'tr-4', icon: '🧐', label: 'Furo Roteiro', type: 'cinema_error', color: 'Orange', tooltip: 'Nota de consistência, lógica ou incoerência na cena.' },
      { id: 'tr-5', icon: '📝', label: 'Subtexto/Tom', type: 'cinema_note', color: 'Cyan', tooltip: 'Observação do Diretor sobre a intenção velada.' },
      { id: 'tr-6', icon: '💬', label: 'Nota Livre', type: 'comment', tooltip: 'Comentário espontâneo do autor ou equipe.' },
    ],
  },
  dept_heads: {
    id: 'dept_heads',
    name: 'Reunião de Direção e Chefes de Equipe',
    icon: '👥',
    category: '🎬 Produção de Cinema',
    description: 'Gestão visual entre Direção, DPs, Arte e Figurinos.',
    defaultButtons: [
      { id: 'dh-1', icon: '📷', label: 'Fotografia/Luz', type: 'action', tooltip: 'Notas e direcionamento para lentes, enquadramentos e clima.' },
      { id: 'dh-2', icon: '🎨', label: 'Cenografia/Arte', type: 'action', tooltip: 'Ideias de adereços de set, móveis e cores.' },
      { id: 'dh-3', icon: '🔊', label: 'Som Direto', type: 'action', tooltip: 'Desafios acústicos ou demandas de efeitos sonoros em set.' },
      { id: 'dh-4', icon: '🧥', label: 'Figurino/Grip', type: 'action', tooltip: 'Notas de roupas dos personagens ou montagem mecânica.' },
      { id: 'dh-5', icon: '📅', label: 'Cronograma', type: 'decision', color: 'Green', tooltip: 'Data-limite ou prioridades de gravação de diária.' },
      { id: 'dh-6', icon: '💰', label: 'Custos/Insumo', type: 'action', color: 'Orange', tooltip: 'Discussão de verbas, extras e contingências.' },
    ],
  },
  decupagem: {
    id: 'decupagem',
    name: 'Decupagem & Plano de Produção',
    icon: '📹',
    category: '🎬 Produção de Cinema',
    description: 'Análise descritiva de cada plano para câmera e grua.',
    defaultButtons: [
      { id: 'dec-1', icon: '📹', label: 'Enquadramento', type: 'action', tooltip: 'Definição de tamanho (Geral, Close, Detalhe).' },
      { id: 'dec-2', icon: '🔄', label: 'Movimento Câm.', type: 'action', tooltip: 'Travelling, panorâmica, grua ou câmera na mão.' },
      { id: 'dec-3', icon: '⚡', label: 'Lente/Filtro', type: 'action', tooltip: 'Uso de milimetragem (Ex: 35mm), filtros ou bokeh.' },
      { id: 'dec-4', icon: '⏱️', label: 'Duração Toma.', type: 'action', tooltip: 'Duração rítmica estimada da coreografia de cena.' },
      { id: 'dec-5', icon: '🚧', label: 'Dublê/Efeito', type: 'action', color: 'Orange', tooltip: 'Atenção redobrada para segurança de equipe e fumaça.' },
      { id: 'dec-6', icon: '💡', label: 'Demanda Elétr.', type: 'comment', tooltip: 'Necessidade de gerador extra ou iluminação móvel.' },
    ],
  },
  scouting: {
    id: 'scouting',
    name: 'Visitas Técnicas (Scouting)',
    icon: '📍',
    category: '🎬 Produção de Cinema',
    description: 'Mapeamento de fiação, luz e poluição sonora em locações.',
    defaultButtons: [
      { id: 'sco-1', icon: '📍', label: 'Ângulo Principal', type: 'location', tooltip: 'Melhor posição estratégica para posicionar o set.' },
      { id: 'sco-2', icon: '☀️', label: 'Caminho do Sol', type: 'action', tooltip: 'Posição solar nas faixas da manhã, tarde e poente.' },
      { id: 'sco-3', icon: '🔊', label: 'Invasão Sonora', type: 'cinema_error', color: 'Orange', tooltip: 'Ruídos de vias expressas, obras ou vizinhos próximos.' },
      { id: 'sco-4', icon: '🔌', label: 'Energia do Local', type: 'action', tooltip: 'Disjuntores livres, potência e amperagem disponível.' },
      { id: 'sco-5', icon: '🚗', label: 'Estacionam./Grip', type: 'action', tooltip: 'Armazenamento de equipe técnica e furgões da câmera.' },
      { id: 'sco-6', icon: '⚠️', label: 'Alvará/Lei de Set', type: 'cinema_error', color: 'Orange', tooltip: 'Notas sobre autorizações de filmagem urbanas.' },
    ],
  },
  briefing_montagem: {
    id: 'briefing_montagem',
    name: 'Briefing de Montagem',
    icon: '✂️',
    category: '🎬 Produção de Cinema',
    description: 'Notas rítmicas de corte e trilhas para o editor.',
    defaultButtons: [
      { id: 'bm-1', icon: '✂️', label: 'Marca de Corte', type: 'action', tooltip: 'Gatilho visual ou fônico indicado para transição.' },
      { id: 'bm-2', icon: '👥', label: 'Descarte Performance', type: 'cinema_error', color: 'Orange', tooltip: 'Takes bons em que deve ser cortada a fala final irritante.' },
      { id: 'bm-3', icon: '⏳', label: 'Compasso/Pacing', type: 'action', tooltip: 'Notas para cortes secos rápidos versus contemplações.' },
      { id: 'bm-4', icon: '🔊', label: 'Foley/Ambiente', type: 'comment', tooltip: 'Localização de efeitos sonoros cruciais para reforçar suspense.' },
      { id: 'bm-5', icon: '🎨', label: 'Saturação/Tint', type: 'action', tooltip: 'Nota para a grade de colorização e calor cromático.' },
      { id: 'bm-6', icon: '✨', label: 'Inserir CGI/3D', type: 'action', color: 'Cyan', tooltip: 'Cena que requer tela azul/verde para montagem de efeitos.' },
    ],
  },
  filme_comentado: {
    id: 'filme_comentado',
    name: 'Filme Comentado',
    icon: '🗣️',
    category: '🎬 Produção de Cinema',
    description: 'Gravações para faixas de comentário do diretor e extras.',
    defaultButtons: [
      { id: 'fc-1', icon: '💡', label: 'História Curiosa', type: 'comment', tooltip: 'Anotação rápida de causos engraçados do elenco.' },
      { id: 'fc-2', icon: '🎭', label: 'Segredo Atuação', type: 'action', tooltip: 'Técnica de improviso ou reações genuínas na cena.' },
      { id: 'fc-3', icon: '📷', label: 'Efeito Prático', type: 'action', color: 'Green', tooltip: 'Como aquele plano foi filmado sem fios ou truques.' },
      { id: 'fc-4', icon: '🎬', label: 'Fato Deletado', type: 'cinema_note', color: 'Cyan', tooltip: 'Explicação de ideias de roteiro que foram descartadas.' },
      { id: 'fc-5', icon: '🎶', label: 'Escolha de Som', type: 'action', tooltip: 'Fundamentações para faixas de trilha de licenciados.' },
      { id: 'fc-6', icon: '⚠️', label: 'Furo Proposital', type: 'cinema_error', color: 'Orange', tooltip: 'Curiosidades de continuidades ignoradas por diversão.' },
    ],
  },
  journalism: {
    id: 'journalism',
    name: 'Jornalismo de Campo',
    icon: '🎤',
    category: '🎥 Audiovisual & Comunicação',
    description: 'Acelera a ilha de edição na TV.',
    defaultButtons: [
      { id: 'jor-1', icon: '🎥', label: 'B-Roll', type: 'action', tooltip: 'Marca imagens de cobertura (B-Roll).' },
      { id: 'jor-2', icon: '🌟', label: 'VIP', type: 'person', tooltip: 'Sinaliza a aparição de uma pessoa importante.' },
      { id: 'jor-3', icon: '🎙️', label: 'Polêmica', type: 'action', tooltip: 'Destaca uma declaração controversa.' },
      { id: 'jor-4', icon: '💥', label: 'Tumulto', type: 'action', tooltip: 'Marca um momento de confusão ou ação intensa.' },
      { id: 'jor-5', icon: '📝', label: 'Stand-up', type: 'action', tooltip: 'Registra a passagem do repórter (Stand-up).' },
      { id: 'jor-6', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Adiciona uma nota para o editor.' },
      { id: 'jor-7', icon: '🗣️', label: 'Entrevista', type: 'action', tooltip: 'Marca o início de uma sonora/entrevista.' },
      { id: 'jor-8', icon: '✅', label: 'Fato', type: 'action', tooltip: 'Sinaliza um dado ou fato importante.' },
      { id: 'jor-9', icon: '📍', label: 'Local', type: 'location', tooltip: 'Registra a mudança de locação.' },
      { id: 'jor-10', icon: '🚨', label: 'Urgente', type: 'action', tooltip: 'Destaca uma informação de última hora (Breaking News).' },
    ],
  },
  podcast: {
    id: 'podcast',
    name: 'Podcast & Lives',
    icon: '📻',
    category: '🎥 Audiovisual & Comunicação',
    description: 'Tópicos principais, risos, inserções e piadas.',
    defaultButtons: [
      { id: 'pod-1', icon: '🔥', label: 'Citação', type: 'quote', tooltip: 'Marca uma fala de destaque para usar como citação.' },
      { id: 'pod-2', icon: '🤣', label: 'Controvérsia', type: 'emotion', tooltip: 'Momento engraçado ou debate acalorado.' },
      { id: 'pod-3', icon: '✂️', label: 'Corte', type: 'cut', tooltip: 'Nota de corte na edição.' },
      { id: 'pod-4', icon: '💡', label: 'Pergunta Chave', type: 'action', tooltip: 'Uma ótima indagação que rendeu bela resposta.' },
      { id: 'pod-5', icon: '⏱️', label: 'Capítulo', type: 'action', tooltip: 'Marcação para criação de blocos de tempo.' },
      { id: 'pod-6', icon: '🔊', label: 'Vinheta/Trilha', type: 'action', tooltip: 'Indicação para inserção de trilha extra.' },
      { id: 'pod-7', icon: '⚠️', label: 'Ruído/Erro', type: 'cut', tooltip: 'Interrupção ou ruído para remover depois.' },
      { id: 'pod-8', icon: '💬', label: 'Nota Livre', type: 'comment', tooltip: 'Anotações rápidas em texto real.' },
    ],
  },
  vlog: {
    id: 'vlog',
    name: 'Criação de Conteúdo (Vlog)',
    icon: '📱',
    category: '🎥 Audiovisual & Comunicação',
    description: 'Planeje hooks de impacto e transições.',
    defaultButtons: [
      { id: 'vlg-1', icon: '🪝', label: 'Hook / Gancho', type: 'action', tooltip: 'Início marcante e chamativo.' },
      { id: 'vlg-2', icon: '🎨', label: 'Transição / B-Roll', type: 'action', tooltip: 'Inserção de cobertura ou transição.' },
      { id: 'vlg-3', icon: '📣', label: 'Chamada para Ação', type: 'action', tooltip: 'CTA para curtir, seguir ou comentar.' },
      { id: 'vlg-4', icon: '✂️', label: 'Corte Seco', type: 'cut', tooltip: 'Marcação de respiro ou erro no dialeto.' },
      { id: 'vlg-5', icon: '📦', label: 'Mostra Objeto', type: 'action', tooltip: 'Destaque visual do gadget/produto.' },
      { id: 'vlg-6', icon: '💡', label: 'Ideia Espontânea', type: 'comment', tooltip: 'Uma sacada gerada na gravação.' },
    ],
  },

  // --- Category: Negócios & Trabalho Remoto
  meeting: {
    id: 'meeting',
    name: 'Reunião de Diretoria',
    icon: '🤝',
    category: '👔 Negócios & Trabalho Remoto',
    description: 'Ata automática com tarefas (Action Items) e deves.',
    defaultButtons: [
      { id: 'mtg-1', icon: '✅', label: 'Decisão', type: 'decision', tooltip: 'Registra uma decisão tomada pelo grupo.' },
      { id: 'mtg-2', icon: '📌', label: 'Action Item', type: 'action', tooltip: 'Marca uma tarefa que precisa ser executada.' },
      { id: 'mtg-3', icon: '👤', label: 'Delegação', type: 'person', tooltip: 'Atribui uma responsabilidade a alguém.' },
      { id: 'mtg-4', icon: '💰', label: 'Orçamento', type: 'action', tooltip: 'Sinaliza uma discussão sobre custos ou verba.' },
      { id: 'mtg-5', icon: '🧱', label: 'Blocker', type: 'action', tooltip: 'Marca um impedimento ou problema no projeto.' },
      { id: 'mtg-6', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Adiciona uma nota livre à ata.' },
      { id: 'mtg-7', icon: '💡', label: 'Ideia', type: 'action', tooltip: 'Destaca uma sugestão ou ideia nova.' },
      { id: 'mtg-8', icon: '🔄', label: 'Follow-up', type: 'action', tooltip: 'Marca um assunto que precisa de acompanhamento.' },
    ],
  },
  brainstorm: {
    id: 'brainstorm',
    name: 'Brainstorming & Ideação',
    icon: '💡',
    category: '👔 Negócios & Trabalho Remoto',
    description: 'Coparticipação de ideias fora da caixa e MVP.',
    defaultButtons: [
      { id: 'brn-1', icon: '💡', label: 'Ideia de Impacto', type: 'decision', tooltip: 'Uma proposta de grande valor e fácil execução.' },
      { id: 'brn-2', icon: '🚀', label: 'Disruptivo / Ousado', type: 'action', tooltip: 'Conceito altamente inovador, fora da caixa.' },
      { id: 'brn-3', icon: '⚠️', label: 'Risco / Desafio', type: 'action', tooltip: 'Barreiras técnicas, financeiras ou mercadológicas mapeadas.' },
      { id: 'brn-4', icon: '🛠️', label: 'Implementação / MVP', type: 'action', tooltip: 'Ideia prática de como colocar em prática ou simplificar.' },
      { id: 'brn-5', icon: '🎯', label: 'Público / Persona', type: 'person', tooltip: 'Foco no perfil do cliente ou público beneficiado.' },
      { id: 'brn-6', icon: '💥', label: 'Pivotar / Descartar', type: 'cut', tooltip: 'Identifica abordagens para descartar ou reformular.' },
      { id: 'brn-7', icon: '📊', label: 'Próximos Passos', type: 'action', tooltip: 'Próximas ações diretas para validar e estruturar a ideia.' },
      { id: 'brn-8', icon: '💬', label: 'Anotação Livre', type: 'comment', tooltip: 'Anotações gerais e links inspiracionais chave.' },
    ],
  },
  recruitment: {
    id: 'recruitment',
    name: 'Candidato & Recrutamento',
    icon: '👥',
    category: '👔 Negócios & Trabalho Remoto',
    description: 'Entrevistas de emprego e análise de soft skills.',
    defaultButtons: [
      { id: 'rec-1', icon: '⭐', label: 'Ponto Forte', type: 'action', tooltip: 'Competência técnica ou destaque positivo do candidato.' },
      { id: 'rec-2', icon: '⚠️', label: 'Red Flag', type: 'action', tooltip: 'Inconsistência ou preocupação de perfil/compatibilidade.' },
      { id: 'rec-3', icon: '💬', label: 'Perg. Técnica', type: 'comment', tooltip: 'Análise de resposta prática/case avaliado.' },
      { id: 'rec-4', icon: '🤝', label: 'Fator Cultural', type: 'decision', tooltip: 'Compatibilidade com os costumes e valores da firma.' },
      { id: 'rec-5', icon: '💰', label: 'Pretensão/Sal.', type: 'action', tooltip: 'Pretensão, benefícios ou restrições de horários e contratos.' },
    ],
  },
  pitch: {
    id: 'pitch',
    name: 'Apresentações (Sales Pitch)',
    icon: '📊',
    category: '👔 Negócios & Trabalho Remoto',
    description: 'Destaques comerciais e objeções de investidor.',
    defaultButtons: [
      { id: 'pit-1', icon: '🎯', label: 'Objeção Cliente', type: 'action', tooltip: 'Barreira comercial levantada pelo investidor ou comprador.' },
      { id: 'pit-2', icon: '🔑', label: 'Valor Chave', type: 'decision', tooltip: 'Característica do software/fator elogiado.' },
      { id: 'pit-3', icon: '💸', label: 'Orçamento/Preço', type: 'action', tooltip: 'Discussão sobre preço contratado, descontos ou faturas.' },
      { id: 'pit-4', icon: '📅', label: 'Retorno/Task', type: 'action', tooltip: 'Compromisso com data estipulada para follow-up ou call.' },
      { id: 'pit-5', icon: '⚡', label: 'Competidor', type: 'comment', tooltip: 'Menção a concorrentes de mercado.' },
    ],
  },

  // --- Category: Operações, Suporte & Vistoria
  support: {
    id: 'support',
    name: 'Suporte (Sucesso do Cliente)',
    icon: '📞',
    category: '🛠️ Operações, Suporte & Vistoria',
    description: 'Captura relatos de falhas, pontos fortes e opiniões.',
    defaultButtons: [
      { id: 'sup-1', icon: '🐛', label: 'Bug / Bug de UX', type: 'action', tooltip: 'Erro relatado pelo usuário final do sistema.' },
      { id: 'sup-2', icon: '💡', label: 'Feature Request', type: 'action', tooltip: 'Pedido de nova funcionalidade ou melhoramento.' },
      { id: 'sup-3', icon: '🥵', label: 'Atrito Elevado', type: 'emotion', tooltip: 'Momento de impaciência ou chateação do usuário.' },
      { id: 'sup-4', icon: '💖', label: 'Elogio/Amor', type: 'emotion', tooltip: 'Satisfação do cliente com os serviços ou atendente.' },
      { id: 'sup-5', icon: '💬', label: 'Solução Sugerida', type: 'decision', tooltip: 'Conselho ou contorno para a tratativa do chamado.' },
    ],
  },
  workshop: {
    id: 'workshop',
    name: 'Workshops & Treinamentos',
    icon: '📝',
    category: '🛠️ Operações, Suporte & Vistoria',
    description: 'Anote dúvidas, feedbacks e exercícios em grupo.',
    defaultButtons: [
      { id: 'wrk-1', icon: '❓', label: 'Dúvida Frequente', type: 'comment', tooltip: 'Questão importante trazida pelos integrantes.' },
      { id: 'wrk-2', icon: '🔨', label: 'Prática/Exercício', type: 'action', tooltip: 'Início de um laboratório ou dinâmica prática.' },
      { id: 'wrk-3', icon: '🌟', label: 'Feedback Positivo', type: 'emotion', tooltip: 'Destaque e motivação do facilitador.' },
      { id: 'wrk-4', icon: '🚀', label: 'Ideia Prática', type: 'decision', tooltip: 'Conselho imediato para os estudos individuais.' },
    ],
  },
  construction: {
    id: 'construction',
    name: 'Diário de Obra (Engenharia)',
    icon: '👷',
    category: '🛠️ Operações, Suporte & Vistoria',
    description: 'Dite avanço físico, insumos e atrasos na obra.',
    defaultButtons: [
      { id: 'con-1', icon: '🧱', label: 'Material/Insumo', type: 'action', tooltip: 'Chegada, falta ou análise de qualidade do material.' },
      { id: 'con-2', icon: '⚠️', label: 'Impedimento/Atraso', type: 'action', tooltip: 'Gargalo físico que paralisou a execução do serviço.' },
      { id: 'con-3', icon: '🏗️', label: 'Fase Finalizada', type: 'decision', tooltip: 'Andamento aprovado e finalizado na edificação.' },
      { id: 'con-4', icon: '👷', label: 'Equipe de Campo', type: 'person', tooltip: 'Alocação ou reclamação sobre mão-de-obra.' },
      { id: 'con-5', icon: '🛡️', label: 'Falha Técnica', type: 'action', tooltip: 'Irregularidade de segurança ou erros do projeto civíl.' },
    ],
  },
  inspection: {
    id: 'inspection',
    name: 'Vistoria & Inspeção Técnica',
    icon: '🚗',
    category: '🛠️ Operações, Suporte & Vistoria',
    description: 'Checklists auditados por comandos de voz.',
    defaultButtons: [
      { id: 'ins-1', icon: '🔴', label: 'Não Conforme', type: 'action', tooltip: 'Defeito, risco de pane ou vazamento encontrado.' },
      { id: 'ins-2', icon: '🟢', label: 'Conforme', type: 'decision', tooltip: 'Item em perfeitas condições analisado.' },
      { id: 'ins-3', icon: '⚠️', label: 'Grave/Reformar', type: 'action', tooltip: 'Aviso imediato de risco à saúde ou integridade.' },
      { id: 'ins-4', icon: '📸', label: 'Pedir Foto', type: 'action', tooltip: 'Anotar necessidade urgente de registro visual dantesco.' },
    ],
  },

  // --- Category: Educação, Ciência & Saúde
  medical_doctor: {
    id: 'medical_doctor',
    name: 'Prontuário Médico (Médico)',
    icon: '🩺',
    category: '🧠 Educação, Ciência & Saúde',
    description: 'Transforma a conversa em prontuário clínico.',
    defaultButtons: [
      { id: 'med-doc-1', icon: '💊', label: 'Prescrição', type: 'action', tooltip: 'Marca la indicação de um medicamento.' },
      { id: 'med-doc-2', icon: '🤧', label: 'Sintoma', type: 'action', tooltip: 'Registra um sintoma relatado pelo paciente.' },
      { id: 'med-doc-3', icon: '🩺', label: 'Diagnóstico', type: 'decision', tooltip: 'Marca a definição de uma hipótese diagnóstica.' },
      { id: 'med-doc-4', icon: '📅', label: 'Retorno', type: 'action', tooltip: 'Sinaliza o agendamento de uma nova consulta.' },
      { id: 'med-doc-5', icon: '📋', label: 'Pedir Exame', type: 'action', tooltip: 'Registra a solicitação de exames.' },
      { id: 'med-doc-6', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Adiciona uma observação clínica.' },
      { id: 'med-doc-7', icon: '⚠️', label: 'Alergia', type: 'action', tooltip: 'Destaca uma alergia informada pelo paciente.' },
    ],
  },
  lecture: {
    id: 'lecture',
    name: 'Palestras & Aulas',
    icon: '👨‍🏫',
    category: '🧠 Educação, Ciência & Saúde',
    description: 'Foco em retenção de conhecimento acadêmico.',
    defaultButtons: [
      { id: 'lec-1', icon: '🚨', label: 'Cai na Prova', type: 'action', tooltip: 'Marca um assunto importante para avaliações.' },
      { id: 'lec-2', icon: '❓', label: 'Não Entendi', type: 'action', tooltip: 'Sinaliza um trecho confuso para revisar depois.' },
      { id: 'lec-3', icon: '📚', label: 'Referência', type: 'action', tooltip: 'Marca a indicação de um livro, artigo ou autor.' },
      { id: 'lec-4', icon: '📅', label: 'Data da Prova', type: 'action', tooltip: 'Registra o anúncio de uma data importante.' },
      { id: 'lec-5', icon: '🖼️', label: 'Novo Slide', type: 'action', tooltip: 'Indica a mudança para um novo slide ou tópico.' },
      { id: 'lec-6', icon: '💬', label: 'Comentário', type: 'comment', tooltip: 'Adiciona uma anotação pessoal.' },
    ],
  },
  research: {
    id: 'research',
    name: 'Pesquisa Laboratorial',
    icon: '🔬',
    category: '🧠 Educação, Ciência & Saúde',
    description: 'Registro de hipóteses exatas e dados relevantes.',
    defaultButtons: [
      { id: 'res-1', icon: '📊', label: 'Dado Importante', type: 'action', tooltip: 'Registra a captura de um dado de extrema relevância.' },
      { id: 'res-2', icon: '❌', label: 'Divergência', type: 'action', tooltip: 'Marca um ponto de discordância ou inconformidade científica.' },
      { id: 'res-3', icon: '🧪', label: 'Nova Hipótese', type: 'decision', tooltip: 'Sinaliza alteração na metodologia ou nova tese.' },
      { id: 'res-4', icon: '💡', label: 'Insight', type: 'comment', tooltip: 'Ideia boa gerada na mesa de estudo.' },
    ],
  },
  writing: {
    id: 'writing',
    name: 'Criação Literária',
    icon: '✍️',
    category: '🧠 Educação, Ciência & Saúde',
    description: 'Para roteiristas e autores tecerem contos ricos.',
    defaultButtons: [
      { id: 'wrt-1', icon: '👤', label: 'Hero / Vilão', type: 'person', tooltip: 'Ficha rápida de personagem que entra em pauta.' },
      { id: 'wrt-2', icon: '🗺️', label: 'Universo / Mapa', type: 'location', tooltip: 'Marca detalhes sobre o ambiente ou mundo.' },
      { id: 'wrt-3', icon: '🤯', label: 'Plot Twist', type: 'action', tooltip: 'Uma guinada profunda planejada na escrita.' },
      { id: 'wrt-4', icon: '⚠️', label: 'Furo / Lógica', type: 'action', tooltip: 'Identificação de problemas de consistência ou regras.' },
      { id: 'wrt-5', icon: '💬', label: 'Nota Rápida', type: 'comment', tooltip: 'Análise literária instantânea sob a voz.' },
    ],
  },
  medical_patient: {
    id: 'medical_patient',
    name: 'Consulta Médica (Paciente)',
    icon: '🧑‍⚕️',
    category: '🧠 Educação, Ciência & Saúde',
    description: 'Resumo simples e guia prático para o doente.',
    defaultButtons: [
      { id: 'med-pat-1', icon: '❓', label: 'Dúvida Paciente', type: 'comment', tooltip: 'Dúvida ou pergunta direta ao doutor.' },
      { id: 'med-pat-2', icon: '💊', label: 'Medicamento', type: 'action', tooltip: 'Como, quando e por quanto tempo tomar o remédio.' },
      { id: 'med-pat-3', icon: '📅', label: 'Próxima Visita', type: 'action', tooltip: 'Definição de data para retornos.' },
      { id: 'med-pat-4', icon: '🥗', label: 'Alimentação', type: 'action', tooltip: 'Instruções dietéticas fornecidas pelo terapeuta.' },
    ],
  },

  // --- Category: Vida Pessoal & Lazer
  bar_conversa: {
    id: 'bar_conversa',
    name: 'Conversa de Bar',
    icon: '🍻',
    category: '🏡 Vida Pessoal & Lazer',
    description: 'Casos, resenhas e filosofias descontraídas.',
    defaultButtons: [
      { id: 'bar-1', icon: '🍻', label: 'Brinde/Tim-Tim', type: 'action', tooltip: 'Marca momento alegre de saúde.' },
      { id: 'bar-2', icon: '🤣', label: 'História Boa', type: 'emotion', tooltip: 'Caso ou piada digna de registro.' },
      { id: 'bar-3', icon: '🎸', label: 'Som / Indicação', type: 'action', tooltip: 'Playlist, banda ou música recomendada.' },
      { id: 'bar-4', icon: '🍔', label: 'Conta / Rateio', type: 'action', tooltip: 'Custo, comissão de garçom ou divisão de faturas.' },
      { id: 'bar-5', icon: '🗣️', label: 'Pras Sete Chaves', type: 'quote', tooltip: 'Fofocas quentes ou segredos profundos revelados.' },
    ],
  },
  party_planning: {
    id: 'party_planning',
    name: 'Planejamento de Festa',
    icon: '🎉',
    category: '🏡 Vida Pessoal & Lazer',
    description: 'Vaquinhas, decorações e buffet da festa.',
    defaultButtons: [
      { id: 'part-1', icon: '🎁', label: 'Ideia Surpresa', type: 'comment', tooltip: 'Presentes, pegadinhas ou atos surpresas.' },
      { id: 'part-2', icon: '🥗', label: 'Comes / Bebes', type: 'action', tooltip: 'Quantidades e lista de iguarias para compra.' },
      { id: 'part-3', icon: '💰', label: 'Rateio / Pix', type: 'decision', tooltip: 'Valores individuais decididos para cobrança.' },
      { id: 'part-4', icon: '👥', label: 'Lista Prévia', type: 'person', tooltip: 'Confirmação aproximada de totalizadores.' },
    ],
  },
  travel_diary: {
    id: 'travel_diary',
    name: 'Diário de Bordo (Viagens)',
    icon: '✈️',
    category: '🏡 Vida Pessoal & Lazer',
    description: 'Eternize atrações, gastos e pratos exóticos.',
    defaultButtons: [
      { id: 'trv-1', icon: '📍', label: 'Visita / Local', type: 'location', tooltip: 'Prédio, museu, praia ou atração conhecida.' },
      { id: 'trv-2', icon: '🍲', label: 'Comida Exótica', type: 'action', tooltip: 'Avaliação de sabor e custo da janta.' },
      { id: 'trv-3', icon: '💰', label: 'Despesa/Câmbio', type: 'action', tooltip: 'Conversão ou gasto efetuado no cartão.' },
      { id: 'trv-4', icon: '🌟', label: 'Melhor Dica', type: 'decision', tooltip: 'Dica alta para outros viajantes ou retrospectiva.' },
    ],
  },
  family_history: {
    id: 'family_history',
    name: 'Histórias de Família',
    icon: '👵',
    category: '🏡 Vida Pessoal & Lazer',
    description: 'Causos de avós, origens e genealogia.',
    defaultButtons: [
      { id: 'fam-1', icon: '🌳', label: 'Família / Árvore', type: 'person', tooltip: 'Nomes de membros para a linhagem.' },
      { id: 'fam-2', icon: '🗓️', label: 'Era Tempos Atrás', type: 'action', tooltip: 'Data, década ou período recordável.' },
      { id: 'fam-3', icon: '📍', label: 'Imigração/Lugar', type: 'location', tooltip: 'Região dantesca de moradia.' },
      { id: 'fam-4', icon: '📖', label: 'Causo Marcante', type: 'quote', tooltip: 'Histórias ricas de aprendizados ou risadas.' },
    ],
  },
};
